version: '3.3'

services:
  learn_postgresql_master:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: 'pg_master'
    ports:
      - '65003:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'LearnPostgreSQL16'
      POSTGRES_DB: 'postgres'
      PGDATA: '/postgres/16/data'
      SERVER_NAME: 'pg_master'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ~/LearnPostgreSQL/docker-vols/chapter17_sync_master/data:/postgres/16/data
 
  learn_postgresql_replica:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: 'pg_replica'
    ports:
      - '65004:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'LearnPostgreSQL16'
      POSTGRES_DB: 'postgres'
      PGDATA: '/postgres/16/data'
      SERVER_NAME: 'pg_replica'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ~/LearnPostgreSQL/docker-vols/chapter17_sync_replica/data:/postgres/16/data
