version: '3.3'

services:
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: 'pg-destination'
    ports:
      - '63127:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'LearnPostgreSQL'
      POSTGRES_DB: 'postgres'
      PGDATA: '/var/lib/postgresql/data'
      SERVER_NAME: 'postgresql'
    volumes:
      - ./postgresql-init:/docker-entrypoint-initdb.d/
      - ~/LearnPostgreSQL/docker-vols/chapter19/chapter19-pg-destination:/var/lib/postgresql/data

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    hostname: 'mariadb-source'
    restart: always
    environment:
      MYSQL_DATABASE: 'mysql'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'LearnPostgreSQL'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'LearnPostgreSQL'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '63128:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d/
      - ~/LearnPostgreSQL/docker-vols/chapter19/chapter19-mariadb-source:/var/lib/mysql
