version: '3.3'

services:
  pg_fdw1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: 'pg_fdw1'
    ports:
      - '65020:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'LearnPostgreSQL16'
      POSTGRES_DB: 'postgres'
      PGDATA: '/postgres/16/data'
      SERVER_NAME: 'pg_fdw1'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ~/LearnPostgreSQL/docker-vols/chapter19/chapter19-postgresql_fdw1:/postgres/16/data

  pg_fdw2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: 'pg_fdw2'
    ports:
      - '65021:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'LearnPostgreSQL16'
      POSTGRES_DB: 'postgres'
      PGDATA: '/postgres/16/data'
      SERVER_NAME: 'pg_fdw2'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ~/LearnPostgreSQL/docker-vols/chapter19/chapter19-postgresql_fdw2:/postgres/16/data
