version: '3.3'

services:
  learn_postgresql_master_pub:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: 'pg_master_pub'
    ports:
      - '65001:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'LearnPostgreSQL16'
      POSTGRES_DB: 'postgres'
      PGDATA: '/postgres/16/data'
      SERVER_NAME: 'pg_master_pub'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ~/LearnPostgreSQL/docker-vols/chapter18_logical_master_pub/data:/postgres/16/data
 
  learn_postgresql_replica:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: 'pg_replica'
    ports:
      - '65002:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'LearnPostgreSQL16'
      POSTGRES_DB: 'postgres'
      PGDATA: '/postgres/16/data'
      SERVER_NAME: 'pg_replica'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ~/LearnPostgreSQL/docker-vols/chapter18_logical_replica/data:/postgres/16/data
      
  learn_postgresql_replica_sub:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: 'pg_replica_sub'
    ports:
      - '65003:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'LearnPostgreSQL16'
      POSTGRES_DB: 'postgres'
      PGDATA: '/postgres/16/data'
      SERVER_NAME: 'pg_replica_sub'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ~/LearnPostgreSQL/docker-vols/chapter18_logical_replica_sub/data:/postgres/16/data
